# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d89aac038f5b4afad8b38f7d0ef8623046313408a766c110fa123cfa3dcd532cd6abe1502e1e73f0f2d30d3be88ab85a024bf762a5c32f680be3418764535ace

test:
  secret_key_base: da77c14583bfa48cfbaa83114cea03df4c52cb4fceb7dc4fdfb23537ab5fa71730e130dd4585d1e63b28289b6c1054f195b499296414d5e1e0019326f0d1f7bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
